/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author Dilan
 */
public class AgregarAnimal extends javax.swing.JFrame {

    /**
     * Creates new form Agregar_Animal
     */
    public AgregarAnimal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nuevoAnimalPanel = new javax.swing.JPanel();
        especieLabel = new javax.swing.JLabel();
        especieComboBox = new javax.swing.JComboBox<>();
        edadLabel = new javax.swing.JLabel();
        edadTextField = new javax.swing.JTextField();
        edadLabelAños = new javax.swing.JLabel();
        pesoLabelKilos = new javax.swing.JLabel();
        pesoTextField = new javax.swing.JTextField();
        pesoLabel = new javax.swing.JLabel();
        paisOrigenComboBox = new javax.swing.JComboBox<>();
        paisOrigenLabel = new javax.swing.JLabel();
        dietaLabel = new javax.swing.JLabel();
        dietaComboBox = new javax.swing.JComboBox<>();
        confirmar = new javax.swing.JButton();
        sectorLabel = new javax.swing.JLabel();
        sectorComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        nuevoAnimalPanel.setBackground(new java.awt.Color(0, 0, 0));

        especieLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        especieLabel.setForeground(new java.awt.Color(255, 255, 255));
        especieLabel.setText("Especie");

        especieComboBox.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        especieComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        edadLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        edadLabel.setForeground(new java.awt.Color(255, 255, 255));
        edadLabel.setText("Edad");

        edadTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        edadLabelAños.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        edadLabelAños.setForeground(new java.awt.Color(255, 255, 255));
        edadLabelAños.setText("años");

        pesoLabelKilos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        pesoLabelKilos.setForeground(new java.awt.Color(255, 255, 255));
        pesoLabelKilos.setText("kilos");

        pesoTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        pesoLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        pesoLabel.setForeground(new java.awt.Color(255, 255, 255));
        pesoLabel.setText("Peso");

        paisOrigenComboBox.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        paisOrigenComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        paisOrigenLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        paisOrigenLabel.setForeground(new java.awt.Color(255, 255, 255));
        paisOrigenLabel.setText("Pais de Origen");

        dietaLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        dietaLabel.setForeground(new java.awt.Color(255, 255, 255));
        dietaLabel.setText("Dieta");

        dietaComboBox.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        dietaComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        dietaComboBox.setToolTipText("");
        dietaComboBox.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dietaComboBox.setName(""); // NOI18N
        dietaComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dietaComboBoxActionPerformed(evt);
            }
        });

        confirmar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        confirmar.setText("Confirmar");
        confirmar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarActionPerformed(evt);
            }
        });

        sectorLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        sectorLabel.setForeground(new java.awt.Color(255, 255, 255));
        sectorLabel.setText("Sector");

        sectorComboBox.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        sectorComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        sectorComboBox.setToolTipText("");
        sectorComboBox.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sectorComboBox.setName(""); // NOI18N
        sectorComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sectorComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout nuevoAnimalPanelLayout = new javax.swing.GroupLayout(nuevoAnimalPanel);
        nuevoAnimalPanel.setLayout(nuevoAnimalPanelLayout);
        nuevoAnimalPanelLayout.setHorizontalGroup(
            nuevoAnimalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nuevoAnimalPanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(nuevoAnimalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(confirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(nuevoAnimalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(sectorLabel)
                        .addComponent(dietaLabel)
                        .addComponent(paisOrigenLabel)
                        .addComponent(especieLabel)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nuevoAnimalPanelLayout.createSequentialGroup()
                            .addGroup(nuevoAnimalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(nuevoAnimalPanelLayout.createSequentialGroup()
                                    .addComponent(edadLabel)
                                    .addGap(89, 89, 89))
                                .addGroup(nuevoAnimalPanelLayout.createSequentialGroup()
                                    .addComponent(edadTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(edadLabelAños)
                                    .addGap(18, 18, 18)))
                            .addGroup(nuevoAnimalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(nuevoAnimalPanelLayout.createSequentialGroup()
                                    .addComponent(pesoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(pesoLabelKilos))
                                .addComponent(pesoLabel)))
                        .addComponent(especieComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(paisOrigenComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dietaComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sectorComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        nuevoAnimalPanelLayout.setVerticalGroup(
            nuevoAnimalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nuevoAnimalPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(nuevoAnimalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(nuevoAnimalPanelLayout.createSequentialGroup()
                        .addComponent(pesoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(nuevoAnimalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pesoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pesoLabelKilos)
                            .addComponent(edadLabelAños)))
                    .addGroup(nuevoAnimalPanelLayout.createSequentialGroup()
                        .addComponent(especieLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(especieComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(edadLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edadTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addComponent(paisOrigenLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paisOrigenComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(dietaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dietaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sectorLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sectorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(confirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        dietaComboBox.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(nuevoAnimalPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(nuevoAnimalPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dietaComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dietaComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dietaComboBoxActionPerformed

    private void confirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarActionPerformed
        dispose();
    }//GEN-LAST:event_confirmarActionPerformed

    private void sectorComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sectorComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sectorComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarAnimal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton confirmar;
    private javax.swing.JComboBox<String> dietaComboBox;
    private javax.swing.JLabel dietaLabel;
    private javax.swing.JLabel edadLabel;
    private javax.swing.JLabel edadLabelAños;
    private javax.swing.JTextField edadTextField;
    private javax.swing.JComboBox<String> especieComboBox;
    private javax.swing.JLabel especieLabel;
    private javax.swing.JPanel nuevoAnimalPanel;
    private javax.swing.JComboBox<String> paisOrigenComboBox;
    private javax.swing.JLabel paisOrigenLabel;
    private javax.swing.JLabel pesoLabel;
    private javax.swing.JLabel pesoLabelKilos;
    private javax.swing.JTextField pesoTextField;
    private javax.swing.JComboBox<String> sectorComboBox;
    private javax.swing.JLabel sectorLabel;
    // End of variables declaration//GEN-END:variables
}
