/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import modelo.Especie;
import modelo.EspecieCarnivora;
import modelo.EspecieHerbivora;
import modelo.Especies;
import modelo.Pais;
import modelo.Paises;

import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author Dilan
 */
public class AgregarAnimal extends javax.swing.JFrame {
    private Paises listaPaises;
    private Especies listaEspecies;
    
    /**
     * Creates new form Agregar_Animal
     */
    public AgregarAnimal(Paises listaPaises, Especies listaEspecies) {
        this.listaPaises = listaPaises;
        this.listaEspecies = listaEspecies;
        
        initComponents();
        llenarComboPaises(this.listaPaises);
        // llenarComboDieta();
        // FALTA TERMINAR
        llenarComboEspecies(this.listaEspecies);
    }
    
    // Metodos //////////////////////////////////////////////////////////////////////////
    public void llenarComboPaises(Paises listaPaises){
        DefaultComboBoxModel<String> modelo = new DefaultComboBoxModel<>();
        
        for(int i = 0; i < listaPaises.getPaises().size(); i++){
            String opcion = (i + 1) + ". " + listaPaises.getPaises().get(i).getNombre();
            modelo.addElement(opcion);
        }
        
        paisOrigenComboBox.setModel(modelo);
    }
    
    /*public void llenarComboDieta(){
        DefaultComboBoxModel<String> modelo = new DefaultComboBoxModel<>();
        
        modelo.addElement("Carnívoro");
        modelo.addElement("Herbívoro");
        
        dietaComboBox.setModel(modelo);
    }*/
    
    public void llenarComboEspecies(Especies listaEspecies){
        DefaultComboBoxModel<String> modelo = new DefaultComboBoxModel<>();
        
        for(int i = 0; i < listaEspecies.getEspecies().size(); i++){
            // Obtener el nombre de la clase de la especie iesima
            String tipoEspecie = listaEspecies.getEspecies().get(i).getClass().getName().substring(14);
            String nombreEspecie = ((Especie) listaEspecies.getEspecies().get(i)).getNombre();
            
            String opcion = nombreEspecie + " (" + tipoEspecie + ")";
            
            modelo.addElement(opcion);
        }
        
        especieComboBox.setModel(modelo);
    }
    /////////////////////////////////////////////////////////////////////////////////////
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nuevoAnimalPanel = new javax.swing.JPanel();
        especieLabel = new javax.swing.JLabel();
        especieComboBox = new javax.swing.JComboBox<>();
        edadLabel = new javax.swing.JLabel();
        edadTextField = new javax.swing.JTextField();
        edadLabelAños = new javax.swing.JLabel();
        pesoLabelKilos = new javax.swing.JLabel();
        pesoTextField = new javax.swing.JTextField();
        pesoLabel = new javax.swing.JLabel();
        paisOrigenComboBox = new javax.swing.JComboBox<>();
        paisOrigenLabel = new javax.swing.JLabel();
        confirmar = new javax.swing.JButton();
        sectorLabel = new javax.swing.JLabel();
        sectorComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        nuevoAnimalPanel.setBackground(new java.awt.Color(0, 0, 0));

        especieLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        especieLabel.setForeground(new java.awt.Color(255, 255, 255));
        especieLabel.setText("Especie");

        especieComboBox.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        especieComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        edadLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        edadLabel.setForeground(new java.awt.Color(255, 255, 255));
        edadLabel.setText("Edad");

        edadTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        edadLabelAños.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        edadLabelAños.setForeground(new java.awt.Color(255, 255, 255));
        edadLabelAños.setText("años");

        pesoLabelKilos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        pesoLabelKilos.setForeground(new java.awt.Color(255, 255, 255));
        pesoLabelKilos.setText("kilos");

        pesoTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        pesoLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        pesoLabel.setForeground(new java.awt.Color(255, 255, 255));
        pesoLabel.setText("Peso");

        paisOrigenComboBox.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        paisOrigenComboBox.setMaximumRowCount(30);
        paisOrigenComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        paisOrigenLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        paisOrigenLabel.setForeground(new java.awt.Color(255, 255, 255));
        paisOrigenLabel.setText("Pais de Origen");

        confirmar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        confirmar.setText("Confirmar");
        confirmar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarActionPerformed(evt);
            }
        });

        sectorLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        sectorLabel.setForeground(new java.awt.Color(255, 255, 255));
        sectorLabel.setText("Sector");

        sectorComboBox.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        sectorComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        sectorComboBox.setToolTipText("");
        sectorComboBox.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sectorComboBox.setName(""); // NOI18N
        sectorComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sectorComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout nuevoAnimalPanelLayout = new javax.swing.GroupLayout(nuevoAnimalPanel);
        nuevoAnimalPanel.setLayout(nuevoAnimalPanelLayout);
        nuevoAnimalPanelLayout.setHorizontalGroup(
            nuevoAnimalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nuevoAnimalPanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(nuevoAnimalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(nuevoAnimalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(sectorLabel)
                        .addComponent(paisOrigenLabel)
                        .addComponent(especieLabel)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nuevoAnimalPanelLayout.createSequentialGroup()
                            .addGroup(nuevoAnimalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(nuevoAnimalPanelLayout.createSequentialGroup()
                                    .addComponent(edadLabel)
                                    .addGap(89, 89, 89))
                                .addGroup(nuevoAnimalPanelLayout.createSequentialGroup()
                                    .addComponent(edadTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(edadLabelAños)
                                    .addGap(18, 18, 18)))
                            .addGroup(nuevoAnimalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(nuevoAnimalPanelLayout.createSequentialGroup()
                                    .addComponent(pesoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(pesoLabelKilos))
                                .addComponent(pesoLabel)))
                        .addComponent(especieComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(paisOrigenComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sectorComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(confirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        nuevoAnimalPanelLayout.setVerticalGroup(
            nuevoAnimalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nuevoAnimalPanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(sectorLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sectorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81)
                .addGroup(nuevoAnimalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(nuevoAnimalPanelLayout.createSequentialGroup()
                        .addComponent(pesoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(nuevoAnimalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pesoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pesoLabelKilos)
                            .addComponent(edadLabelAños)))
                    .addGroup(nuevoAnimalPanelLayout.createSequentialGroup()
                        .addComponent(especieLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(especieComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(edadLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edadTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addComponent(paisOrigenLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paisOrigenComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(confirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(nuevoAnimalPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nuevoAnimalPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void confirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarActionPerformed
        dispose();
    }//GEN-LAST:event_confirmarActionPerformed

    private void sectorComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sectorComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sectorComboBoxActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton confirmar;
    private javax.swing.JLabel edadLabel;
    private javax.swing.JLabel edadLabelAños;
    private javax.swing.JTextField edadTextField;
    private javax.swing.JComboBox<String> especieComboBox;
    private javax.swing.JLabel especieLabel;
    private javax.swing.JPanel nuevoAnimalPanel;
    private javax.swing.JComboBox<String> paisOrigenComboBox;
    private javax.swing.JLabel paisOrigenLabel;
    private javax.swing.JLabel pesoLabel;
    private javax.swing.JLabel pesoLabelKilos;
    private javax.swing.JTextField pesoTextField;
    private javax.swing.JComboBox<String> sectorComboBox;
    private javax.swing.JLabel sectorLabel;
    // End of variables declaration//GEN-END:variables
}
