/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author Dilan
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMenu = new javax.swing.JPanel();
        botonNuevoAnimal = new javax.swing.JButton();
        botonCalcularComida = new javax.swing.JButton();
        kilosCarnivorosLabel = new javax.swing.JLabel();
        kilosCarnivoros = new javax.swing.JLabel();
        kilosHerbivorosLabel = new javax.swing.JLabel();
        kilosHerbivoros = new javax.swing.JLabel();
        kilosTotalLabel = new javax.swing.JLabel();
        kilosTotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        panelMenu.setBackground(new java.awt.Color(0, 0, 0));

        botonNuevoAnimal.setBackground(new java.awt.Color(0, 0, 0));
        botonNuevoAnimal.setForeground(new java.awt.Color(255, 255, 255));
        botonNuevoAnimal.setText("Agregar Animal");
        botonNuevoAnimal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonNuevoAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNuevoAnimalActionPerformed(evt);
            }
        });

        botonCalcularComida.setBackground(new java.awt.Color(0, 0, 0));
        botonCalcularComida.setForeground(new java.awt.Color(255, 255, 255));
        botonCalcularComida.setText("Calcular Comida");
        botonCalcularComida.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonCalcularComida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCalcularComidaActionPerformed(evt);
            }
        });

        kilosCarnivorosLabel.setForeground(new java.awt.Color(255, 255, 255));
        kilosCarnivorosLabel.setText("Kgs Carnivoros");

        kilosCarnivoros.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        kilosCarnivoros.setForeground(new java.awt.Color(255, 255, 255));
        kilosCarnivoros.setText("0");
        kilosCarnivoros.setToolTipText("");

        kilosHerbivorosLabel.setForeground(new java.awt.Color(255, 255, 255));
        kilosHerbivorosLabel.setText("Kgs Herbivoros");

        kilosHerbivoros.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        kilosHerbivoros.setForeground(new java.awt.Color(255, 255, 255));
        kilosHerbivoros.setText("0");
        kilosHerbivoros.setToolTipText("");

        kilosTotalLabel.setForeground(new java.awt.Color(255, 255, 255));
        kilosTotalLabel.setText("Kgs Total");

        kilosTotal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        kilosTotal.setForeground(new java.awt.Color(255, 255, 255));
        kilosTotal.setText("0");
        kilosTotal.setToolTipText("");

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenuLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botonCalcularComida, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                    .addComponent(botonNuevoAnimal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenuLayout.createSequentialGroup()
                        .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kilosHerbivorosLabel)
                            .addComponent(kilosCarnivorosLabel)
                            .addGroup(panelMenuLayout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(kilosTotal)
                                    .addComponent(kilosHerbivoros)
                                    .addComponent(kilosCarnivoros))))
                        .addGap(46, 46, 46))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenuLayout.createSequentialGroup()
                        .addComponent(kilosTotalLabel)
                        .addGap(62, 62, 62))))
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(botonNuevoAnimal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonCalcularComida)
                .addGap(18, 18, 18)
                .addComponent(kilosCarnivorosLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kilosCarnivoros)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kilosHerbivorosLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kilosHerbivoros)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kilosTotalLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kilosTotal)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonNuevoAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNuevoAnimalActionPerformed
        Agregar_Animal agregarAnimal = new Agregar_Animal();
        agregarAnimal.setVisible(true);
    }//GEN-LAST:event_botonNuevoAnimalActionPerformed

    private void botonCalcularComidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCalcularComidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonCalcularComidaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCalcularComida;
    private javax.swing.JButton botonNuevoAnimal;
    private javax.swing.JLabel kilosCarnivoros;
    private javax.swing.JLabel kilosCarnivorosLabel;
    private javax.swing.JLabel kilosHerbivoros;
    private javax.swing.JLabel kilosHerbivorosLabel;
    private javax.swing.JLabel kilosTotal;
    private javax.swing.JLabel kilosTotalLabel;
    private javax.swing.JPanel panelMenu;
    // End of variables declaration//GEN-END:variables
}
