/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author Dilan
 */
public class Vista_Principal extends javax.swing.JFrame {

    /**
     * Creates new form Vista_Principal
     */
    public Vista_Principal() {
        initComponents();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        sectorPanel1 = new javax.swing.JPanel();
        sectorNumero1 = new javax.swing.JLabel();
        sectorEspecies1 = new javax.swing.JLabel();
        sectorCantidadAnimales1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        sectorPanel2 = new javax.swing.JPanel();
        sectorNumero2 = new javax.swing.JLabel();
        sectorEspecies2 = new javax.swing.JLabel();
        sectorCantidadAnimales2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        sectorPanel3 = new javax.swing.JPanel();
        sectorNumero3 = new javax.swing.JLabel();
        sectorEspecies3 = new javax.swing.JLabel();
        sectorCantidadAnimales3 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        panelMenu = new javax.swing.JPanel();
        botonNuevoAnimal = new javax.swing.JButton();
        botonCalcularComida = new javax.swing.JButton();
        kilosCarnivorosLabel = new javax.swing.JLabel();
        kilosCarnivoros = new javax.swing.JLabel();
        kilosHerbivorosLabel = new javax.swing.JLabel();
        kilosHerbivoros = new javax.swing.JLabel();
        kilosTotalLabel = new javax.swing.JLabel();
        kilosTotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        sectorNumero1.setText("Nro Sector");

        sectorEspecies1.setText("Especies");

        sectorCantidadAnimales1.setText("Cantidad de Animales");

        jLabel1.setText("\"Latitud, Longitud\"");

        javax.swing.GroupLayout sectorPanel1Layout = new javax.swing.GroupLayout(sectorPanel1);
        sectorPanel1.setLayout(sectorPanel1Layout);
        sectorPanel1Layout.setHorizontalGroup(
            sectorPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sectorPanel1Layout.createSequentialGroup()
                .addGroup(sectorPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sectorPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(sectorNumero1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(sectorPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(sectorPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sectorEspecies1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sectorPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(sectorCantidadAnimales1)
                .addGap(28, 28, 28))
        );
        sectorPanel1Layout.setVerticalGroup(
            sectorPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sectorPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sectorNumero1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sectorEspecies1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sectorCantidadAnimales1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        sectorNumero2.setText("Nro Sector");

        sectorEspecies2.setText("Especies");

        sectorCantidadAnimales2.setText("Cantidad de Animales");

        jLabel2.setText("\"Latitud, Longitud\"");

        javax.swing.GroupLayout sectorPanel2Layout = new javax.swing.GroupLayout(sectorPanel2);
        sectorPanel2.setLayout(sectorPanel2Layout);
        sectorPanel2Layout.setHorizontalGroup(
            sectorPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sectorPanel2Layout.createSequentialGroup()
                .addGroup(sectorPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sectorPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(sectorNumero2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(sectorPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(sectorPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sectorEspecies2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sectorPanel2Layout.createSequentialGroup()
                .addGap(0, 55, Short.MAX_VALUE)
                .addComponent(sectorCantidadAnimales2)
                .addGap(28, 28, 28))
        );
        sectorPanel2Layout.setVerticalGroup(
            sectorPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sectorPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sectorNumero2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sectorEspecies2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sectorCantidadAnimales2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        sectorNumero3.setText("Nro Sector");

        sectorEspecies3.setText("Especies");

        sectorCantidadAnimales3.setText("Cantidad de Animales");

        jLabel3.setText("\"Latitud, Longitud\"");

        javax.swing.GroupLayout sectorPanel3Layout = new javax.swing.GroupLayout(sectorPanel3);
        sectorPanel3.setLayout(sectorPanel3Layout);
        sectorPanel3Layout.setHorizontalGroup(
            sectorPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sectorPanel3Layout.createSequentialGroup()
                .addGroup(sectorPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sectorPanel3Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(sectorNumero3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(sectorPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sectorPanel3Layout.createSequentialGroup()
                .addGap(0, 55, Short.MAX_VALUE)
                .addComponent(sectorCantidadAnimales3)
                .addGap(28, 28, 28))
            .addGroup(sectorPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sectorEspecies3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        sectorPanel3Layout.setVerticalGroup(
            sectorPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sectorPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sectorNumero3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sectorEspecies3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(sectorCantidadAnimales3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        panelMenu.setBackground(new java.awt.Color(0, 0, 0));

        botonNuevoAnimal.setBackground(new java.awt.Color(0, 0, 0));
        botonNuevoAnimal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botonNuevoAnimal.setForeground(new java.awt.Color(255, 255, 255));
        botonNuevoAnimal.setText("Agregar Animal");
        botonNuevoAnimal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonNuevoAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNuevoAnimalActionPerformed(evt);
            }
        });

        botonCalcularComida.setBackground(new java.awt.Color(0, 0, 0));
        botonCalcularComida.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botonCalcularComida.setForeground(new java.awt.Color(255, 255, 255));
        botonCalcularComida.setText("Calcular Comida");
        botonCalcularComida.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonCalcularComida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCalcularComidaActionPerformed(evt);
            }
        });

        kilosCarnivorosLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        kilosCarnivorosLabel.setForeground(new java.awt.Color(255, 255, 255));
        kilosCarnivorosLabel.setText("Kgs Carnivoros");

        kilosCarnivoros.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        kilosCarnivoros.setForeground(new java.awt.Color(255, 255, 255));
        kilosCarnivoros.setText("0");
        kilosCarnivoros.setToolTipText("");

        kilosHerbivorosLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        kilosHerbivorosLabel.setForeground(new java.awt.Color(255, 255, 255));
        kilosHerbivorosLabel.setText("Kgs Herbivoros");

        kilosHerbivoros.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        kilosHerbivoros.setForeground(new java.awt.Color(255, 255, 255));
        kilosHerbivoros.setText("0");
        kilosHerbivoros.setToolTipText("");

        kilosTotalLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        kilosTotalLabel.setForeground(new java.awt.Color(255, 255, 255));
        kilosTotalLabel.setText("Kgs Total");

        kilosTotal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        kilosTotal.setForeground(new java.awt.Color(255, 255, 255));
        kilosTotal.setText("0");
        kilosTotal.setToolTipText("");

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenuLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botonCalcularComida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonNuevoAnimal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kilosHerbivorosLabel)
                    .addComponent(kilosCarnivorosLabel))
                .addGap(46, 46, 46))
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMenuLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(kilosTotalLabel))
                    .addGroup(panelMenuLayout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(kilosCarnivoros))
                    .addGroup(panelMenuLayout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(kilosHerbivoros))
                    .addGroup(panelMenuLayout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(kilosTotal)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(botonNuevoAnimal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonCalcularComida)
                .addGap(18, 18, 18)
                .addComponent(kilosCarnivorosLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kilosCarnivoros)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kilosHerbivorosLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kilosHerbivoros)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(kilosTotalLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kilosTotal)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sectorPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sectorPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(102, 102, 102)
                .addComponent(panelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(76, 76, 76))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(65, 65, 65)
                    .addComponent(sectorPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(378, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(174, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(sectorPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(sectorPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(panelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(129, 129, 129))))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(62, 62, 62)
                    .addComponent(sectorPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(423, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonNuevoAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNuevoAnimalActionPerformed
        Agregar_Animal agregarAnimal = new Agregar_Animal();
        agregarAnimal.setVisible(true);
    }//GEN-LAST:event_botonNuevoAnimalActionPerformed

    private void botonCalcularComidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCalcularComidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonCalcularComidaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCalcularComida;
    private javax.swing.JButton botonNuevoAnimal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel kilosCarnivoros;
    private javax.swing.JLabel kilosCarnivorosLabel;
    private javax.swing.JLabel kilosHerbivoros;
    private javax.swing.JLabel kilosHerbivorosLabel;
    private javax.swing.JLabel kilosTotal;
    private javax.swing.JLabel kilosTotalLabel;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JLabel sectorCantidadAnimales1;
    private javax.swing.JLabel sectorCantidadAnimales2;
    private javax.swing.JLabel sectorCantidadAnimales3;
    private javax.swing.JLabel sectorEspecies1;
    private javax.swing.JLabel sectorEspecies2;
    private javax.swing.JLabel sectorEspecies3;
    private javax.swing.JLabel sectorNumero1;
    private javax.swing.JLabel sectorNumero2;
    private javax.swing.JLabel sectorNumero3;
    private javax.swing.JPanel sectorPanel1;
    private javax.swing.JPanel sectorPanel2;
    private javax.swing.JPanel sectorPanel3;
    // End of variables declaration//GEN-END:variables
}
